name: mmets
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1



dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  google_fonts: ^6.2.1
  contentsize_tabbarview: ^0.0.2
  dotted_border: ^2.1.0
  flutter_spinkit: ^5.2.1
  pinput: ^5.0.1
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  logger: ^2.0.1
  shared_preferences: ^2.3.5
  mime: ^2.0.0
  file_picker: ^9.1.0
  fl_chart: ^1.0.0
  dash_chat_2: ^0.0.21
  google_maps_flutter: ^2.12.0
  google_places_flutter: ^2.1.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  permission_handler: ^11.4.0


dependency_overrides:
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/